---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ndb-cluster-server-config
  namespace: ndb-cluster
immutable: true
data:
  my.cnf: |+
    # ---------------------------------------------------------------------------------
    [mysqld]
    user                = mysql
    bind-address        = 0.0.0.0
    port                = 3306
    mysqlx-bind-address = 0.0.0.0
    socket              = /var/run/mysqld/mysqld.sock
    mysqlx-socket       = /var/run/mysqld/mysqlx.sock

    datadir             = /var/lib/mysql
    pid-file            = /var/run/mysqld/mysqld.pid
    log-error           = /var/log/mysql/error.log

    ndbcluster
    max_connect_errors  = 10000

    key_buffer_size     = 16M
    thread_stack        = 192K
    thread_cache_size   = 8

    tmpdir              = /tmp
    max_connections     = 100

    #general_log_file   = /var/log/mysql/mysql.log
    #general_log        = 1
    log_error           = /var/log/mysql/error.log

    log_bin             = /var/log/mysql/mysql-bin.log
    max_binlog_size     = 100M
    binlog_do_db        = include_database_name
    binlog_ignore_db    = include_database_name


    # ---------------------------------------------------------------------------------
    [mysql_cluster]
    ndb-connectstring   = ndb-cluster-manager-0.ndb-cluster-manager-svc.ndb-cluster.svc.kube.askug.net,ndb-cluster-manager-1.ndb-cluster-manager-svc.ndb-cluster.svc.kube.askug.net
    ndb-mgmd-host       = ndb-cluster-manager-0.ndb-cluster-manager-svc.ndb-cluster.svc.kube.askug.net,ndb-cluster-manager-1.ndb-cluster-manager-svc.ndb-cluster.svc.kube.askug.net


    # ---------------------------------------------------------------------------------
    [mysql]
    port        = 3306
    socket      = /var/run/mysqld/mysqld.sock


    # ---------------------------------------------------------------------------------
    [mysqldump]
    socket      = /var/run/mysqld/mysqld.sock
    quick
    quote-names
    max_allowed_packet  = 16M


    # ---------------------------------------------------------------------------------
    [mysqladmin]
    socket      = /var/run/mysqld/mysqld.sock
    force


    # ---------------------------------------------------------------------------------
    [mysqld_safe]
    socket      = /var/run/mysqld/mysqld.sock
    nice        = 0


...
