---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cluster-manager-config
  namespace: mysql-cluster
immutable: true
data:
  config.ini: |+
    [ndbd default]
    NoOfReplicas=2

    [ndb_mgmd]
    hostname=cluster-manager-service.mysql-cluster.svc.kube.askug.net
    datadir=/var/lib/mysql-cluster

    [ndbd]
    hostname=cluster-node-2-service.mysql-cluster.svc.kube.askug.net
    NodeId=2
    datadir=/var/lib/mysql/data

    [ndbd]
    hostname=cluster-node-3-service.mysql-cluster.svc.kube.askug.net
    NodeId=3
    datadir=/var/lib/mysql/data

    [mysqld]
    hostname=cluster-server-service.mysql-cluster.svc.kube.askug.net
    # NodeId=4

...
