---
apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-service
  namespace: mysql-cluster
spec:
  selector:
    app: 0ddab094-7554-11ee-904c-b33e59e6adfc
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "http-1186"
      port: 1186
      targetPort: 1186

...

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-cluster-manager-local-service
#   namespace: mysql-cluster
# spec:
#   selector:
#     app: 0ddab094-7554-11ee-904c-b33e59e6adfc
#   clusterIP: None
#   ports:
#   - name: "tcp65535"
#     port: 65535

# ...

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: 0ddab094-7554-11ee-904c-b33e59e6adfc
  name: mysql-cluster-manager
  namespace: mysql-cluster
spec:
  replicas: 1
  serviceName: mysql-cluster
  selector:
    matchLabels:
      app: 0ddab094-7554-11ee-904c-b33e59e6adfc
  template:
    metadata:
      labels:
        app: 0ddab094-7554-11ee-904c-b33e59e6adfc
    spec:
      nodeSelector:
        kubernetes.io/hostname: mp8
      restartPolicy: Always
      hostname: cluster-manager
      # hostname: mysql-cluster-manager
      # subdomain: mysql-cluster-manager-local-service
      hostAliases:
      - ip: 127.0.0.1
        hostnames:
        - cluster-manager-service.mysql-cluster.svc.kube.askug.net

      # initContainers:
      # # ----------------------------------------------------
      # - name: init-cluster-manager
      #   image: busybox:1.36
      #   command: [ "sh", "-c" ]
      #   args: [ "
      #       tail -f /dev/null
      #       # echo \"$POD_IP cluster-manager\" | nc -w 1 mysql-cluster-discovery-srv-service.mysql-cluster.svc.kube.askug.net 5333
      #     " ]
      #   env:
      #   - name: POD_IP
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: status.podIP

      #   resources:
      #     limits:
      #       memory: 64Mi
      #       cpu: 250m
      #     requests:
      #       memory: 32Mi
      #       cpu: 100m


      containers:
      # ----------------------------------------------------
      - name: cluster-manager
        image: hub.askug.net/mysql-cluster-manager-sb-11:0.0.1
        args: [ "-c", "
          sleep 10;
          /usr/sbin/ndb_mgmd
            --config-file=/var/lib/mysql-cluster/config.ini
            --daemon
            --reload
          ;
          tail -f /dev/null
          " ]

        ports:
        - name: tcp1186
          containerPort: 1186
          hostPort: 1186

        # startupProbe:
        #   tcpSocket:
        #     host: mysql-cluster-discovery-srv-service.mysql-cluster.svc.kube.askug.net
        #     port: 53
        #   initialDelaySeconds: 5
        #   periodSeconds: 10

        # livenessProbe:
        #   tcpSocket:
        #     port: tcp1186
        #   initialDelaySeconds: 40
        #   periodSeconds: 10

        # readinessProbe:
        #   tcpSocket:
        #     port: tcp1186
        #   initialDelaySeconds: 40
        #   periodSeconds: 5

        volumeMounts:
        - mountPath: "/var/lib/mysql-cluster/config.ini"
          name: cluster-config
          subPath: "config.ini"
          readOnly: true

        env:
        - name: MYSQL_CLUSTER_MANAGER_VERSION
          value: 8.1.0-1

        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "1"

      # dnsPolicy: "None"
      # dnsConfig:
      #   nameservers:
      #   - 10.203.10.5

      volumes:
      - name: cluster-config
        configMap:
          name: mysql-cluster-manager-config

...
