---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-cluster-server-storage-mp1
  labels:
    file-system: ext4
    physical-volume: lvm-thin-partition
    node-name: mp1
    max-size: 20GiB
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-server-mp1
  local:
    path: /mnt/kube/mysql/server/20
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp1

...
