---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-cluster-server-cache
  namespace: mysql-cluster
  labels:
    maxSize: 10Gi
spec:
  storageClassName: mysql-server-mp1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

...

