---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-cluster-server-storage-mp1
  namespace: mysql-cluster
  labels:
    maxSize: 20Gi
spec:
  storageClassName: mysql-data-server-mp1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

...


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-cluster-server-storage-mp8
  namespace: mysql-cluster
  labels:
    maxSize: 20Gi
spec:
  storageClassName: mysql-data-server-mp8
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

...

