---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cluster-server-config
  namespace: mysql-cluster
immutable: true
data:
  my.cnf: |+
    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mysql.conf.d/

    [mysqld]
    ndbcluster
    max_connect_errors=10000
    
    [mysql_cluster]
    ndb-connectstring=mysql-cluster-manager-mp1-0.cluster-manager-service-mp1.mysql-cluster.svc.kube.askug.net,mysql-cluster-manager-mp1-0.cluster-manager-service-mp8.mysql-cluster.svc.kube.askug.net
    ndb-mgmd-host=mysql-cluster-manager-mp8-0.cluster-manager-service-mp1.mysql-cluster.svc.kube.askug.net,mysql-cluster-manager-mp8-0.cluster-manager-service-mp8.mysql-cluster.svc.kube.askug.net
    

...
