---
apiVersion: v1
kind: Service
metadata:
  name: cluster-server-service-mp8
  namespace: mysql-cluster
spec:
  selector:
    app: c1b580d0-c2a7-11ee-8001-afbcdbf2e051
  # type: ClusterIP
  # clusterIP: None
  type: LoadBalancer
  loadBalancerIP: 10.216.80.36
  ports:
    - protocol: TCP
      name: "tcp3306"
      port: 3306
      targetPort: 3306
    - protocol: TCP
      name: "tcp33060"
      port: 33060
      targetPort: 33060

...


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: c1b580d0-c2a7-11ee-8001-afbcdbf2e051
  name: mysql-cluster-server-mp8
  namespace: mysql-cluster
spec:
  replicas: 1
  serviceName: cluster-server-service-mp8
  selector:
    matchLabels:
      app: c1b580d0-c2a7-11ee-8001-afbcdbf2e051
  template:
    metadata:
      labels:
        app: c1b580d0-c2a7-11ee-8001-afbcdbf2e051
    spec:
      nodeSelector:
        kubernetes.io/hostname: mp8
      restartPolicy: Always

      containers:
      # ----------------------------------------------------
      - name: cluster-server
        image: hub.askug.net/mysql-server-sb-11:0.0.4
        args: [ "-c", "
          while true; do
            if [ $(ls /var/lib/mysql | wc -l) -gt 0 ]; then 
              /usr/sbin/mysqld; 
            else 
              /usr/sbin/mysqld --initialize; 
            fi; 
          done;
          tail -f /dev/null # for debug purpose
          " ]
        # args: [ "-c", "tail -f /dev/null" ]

        ports:
        - name: tcp3306
          containerPort: 3306
          hostPort: 3306
        - name: tcp33060
          containerPort: 33060
          hostPort: 33060

        # startupProbe:
        #   tcpSocket:
        #     host: mysql-cluster-discovery-srv-service.mysql-cluster.svc.kube.askug.net
        #     port: 53
        #   initialDelaySeconds: 5
        #   periodSeconds: 10

        # livenessProbe:
        #   tcpSocket:
        #     port: tcp3306
        #   initialDelaySeconds: 40
        #   periodSeconds: 10

        # readinessProbe:
        #   tcpSocket:
        #     port: tcp3306
        #   initialDelaySeconds: 40
        #   periodSeconds: 5

        volumeMounts:
        - mountPath: "/etc/mysql/my.cnf"
          name: server-config
          subPath: "my.cnf"
          readOnly: true
        - mountPath: "/var/lib/mysql"
          name: mysql-data-volume
          subPath: "mysql-data"
        - mountPath: "/var/log/mysql"
          name: mysql-data-volume
          subPath: "logs"

        env:
        - name: MYSQL_SERVER_VERSION
          value: "8.1"

        resources:
          limits:
            memory: 2Gi
            cpu: "2"
          requests:
            memory: 1Gi
            cpu: "1"

      volumes:
      - name: server-config
        configMap:
          name: mysql-cluster-server-config
      - name: mysql-data-volume
        persistentVolumeClaim:
          claimName: mysql-cluster-server-storage-mp8

...
