---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-node-storage-mp1
  labels:
    file-system: ext4
    node-name: mp1
    physical-volume: lvm-thin-partition
    max-size: 20GiB
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-data-mp1
  local:
    path: /mnt/kube/mysql/node/20
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp1

...

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-node-storage-mp8
  labels:
    file-system: ext4
    node-name: mp8
    physical-volume: lvm-partition
    max-size: 20GiB
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-data-mp8
  local:
    path: /mnt/kube/mysql/node/20
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp8

...
