---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-cluster-data-node-mp1
  namespace: mysql-cluster
  labels:
    maxSize: 20Gi
spec:
  storageClassName: cluster-data-node-mp1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

...

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-cluster-data-node-mp8
  namespace: mysql-cluster
  labels:
    maxSize: 20Gi
spec:
  storageClassName: mysql-data-node-mp8
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

...

