---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cluster-node-config
  namespace: mysql-cluster
immutable: true
data:
  my.cnf: |+
    [mysql_cluster]
    ndb-connectstring=mysql-cluster-manager-mp1-0.cluster-manager-service-mp1.mysql-cluster.svc.kube.askug.net,mysql-cluster-manager-mp8-0.cluster-manager-service-mp8.mysql-cluster.svc.kube.askug.net

    # [mysql]
    # datadir=/var/lib/mysql-data

...
