---
apiVersion: v1
kind: Service
metadata:
  name: cluster-node-3-service
  namespace: mysql-cluster
spec:
  selector:
    app: 1d82738a-75c0-11ee-a527-4feca51b94e8
  type: ClusterIP
  clusterIP: None

...


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: 1d82738a-75c0-11ee-a527-4feca51b94e8
  name: mysql-cluster-data-node-3
  namespace: mysql-cluster
spec:
  replicas: 1
  serviceName: cluster-node-3-service
  selector:
    matchLabels:
      app: 1d82738a-75c0-11ee-a527-4feca51b94e8
  template:
    metadata:
      labels:
        app: 1d82738a-75c0-11ee-a527-4feca51b94e8
    spec:
      nodeSelector:
        kubernetes.io/hostname: mp8
      restartPolicy: Always
      # hostname: cluster-node-3
      # subdomain: cluster-node-3-service
      # hostAliases:
      # - ip: 127.0.0.1
      #   hostnames:
      #   - cluster-node-3-service.mysql-cluster.svc.kube.askug.net

      # initContainers:
      # # ----------------------------------------------------
      # - name: cluster-data-node-3-discovery
      #   image: busybox:1.36
      #   command: [ "sh", "-c" ]
      #   args: [ "
      #       sleep 15
      #       # echo \"$POD_IP cluster-data-node-3\" | nc -w 1 mysql-cluster-discovery-srv-service.mysql-cluster.svc.kube.askug.net 5333
      #     " ]
      #   # env:
      #   # - name: POD_IP
      #   #   valueFrom:
      #   #     fieldRef:
      #   #       fieldPath: status.podIP
      #   resources:
      #     limits:
      #       memory: 64Mi
      #       cpu: 250m
      #     requests:
      #       memory: 32Mi
      #       cpu: 100m

      containers:
      # ----------------------------------------------------
      - name: cluster-data-node-3
        image: hub.askug.net/mysql-cluster-data-node-sb-11:0.0.1
        args: [ "-c", "
          while true; do
            /usr/sbin/ndbd
              --nodaemon
            ;
          done;
          tail -f /dev/null
          " ]

        volumeMounts:
        - mountPath: "/etc/my.cnf"
          name: data-node-config
          subPath: "my.cnf"
          readOnly: true
        - mountPath: "/var/lib/mysql/data"
          name: mysql-data-volume
          subPath: "mysql-data"

        env:
        - name: MYSQL_CLUSTER_DATA_NODE_VERSION
          value: 8.1.0-1

        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            memory: 2Gi
            cpu: "2"

        # startupProbe:
        #   tcpSocket:
        #     host: mysql-cluster-discovery-srv-service.mysql-cluster.svc.kube.askug.net
        #     port: 53
        #   initialDelaySeconds: 5
        #   periodSeconds: 10

      # dnsPolicy: "None"
      # dnsConfig:
      #   nameservers:
      #   - 10.216.80.34

      volumes:
      - name: data-node-config
        configMap:
          name: mysql-cluster-data-node-3-config
      - name: mysql-data-volume
        persistentVolumeClaim:
          claimName: mysql-cluster-data-node-3-cache

...
