---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: 1d82738a-75c0-11ee-a527-4feca51b94e8
  name: mysql-cluster-data-node-3
  namespace: mysql-cluster
spec:
  replicas: 1
  serviceName: mysql-cluster-daemon-3
  selector:
    matchLabels:
      app: 1d82738a-75c0-11ee-a527-4feca51b94e8
  template:
    metadata:
      labels:
        app: 1d82738a-75c0-11ee-a527-4feca51b94e8
    spec:
      nodeSelector:
        node-type: worker
      restartPolicy: Always

      initContainers:
      # ----------------------------------------------------
      - name: cluster-data-node-3-discovery
        image: busybox:1.36
        command: [ "sh", "-c" ]
        args: [ "
            echo \"$POD_IP cluster-data-node-3\" | nc -w 1 mysql-cluster-discovery-srv-service.mysql-cluster.svc.kube.askug.net 5333
          " ]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

      containers:
      # ----------------------------------------------------
      - name: cluster-data-node-3
        image: hub.askug.net/mysql-cluster-data-node-sb-11:0.0.2
        args: [ "-c", "
          /usr/sbin/ndbd
            --nodaemon
          " ]

        volumeMounts:
        - mountPath: "/etc/my.cnf"
          name: data-node-config
          subPath: "my.cnf"
          readOnly: true
        - mountPath: "/var/lib/mysql/data"
          name: mysql-data-volume
          subPath: "mysql-data"

        env:
        - name: MYSQL_CLUSTER_DATA_NODE_VERSION
          value: 8.1.0-1

        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            memory: 2Gi
            cpu: "2"

        startupProbe:
          tcpSocket:
            host: mysql-cluster-discovery-srv-service.mysql-cluster.svc.kube.askug.net
            port: 53
          initialDelaySeconds: 5
          periodSeconds: 10

      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 10.216.80.34

      volumes:
      - name: data-node-config
        configMap:
          name: mysql-cluster-data-node-3-config
      - name: mysql-data-volume
        persistentVolumeClaim:
          claimName: mysql-cluster-data-node-3-cache

...
