---
apiVersion: v1
kind: Service
metadata:
  name: cluster-node-service-mp8
  namespace: mysql-cluster
spec:
  selector:
    app: b967cf84-c2a5-11ee-bfcf-bf4087638bc4
  type: ClusterIP
  clusterIP: None

...


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: b967cf84-c2a5-11ee-bfcf-bf4087638bc4
  name: mysql-cluster-data-node-mp8
  namespace: mysql-cluster
spec:
  replicas: 1
  serviceName: cluster-node-service-mp8
  selector:
    matchLabels:
      app: b967cf84-c2a5-11ee-bfcf-bf4087638bc4
  template:
    metadata:
      labels:
        app: b967cf84-c2a5-11ee-bfcf-bf4087638bc4
    spec:
      nodeSelector:
        kubernetes.io/hostname: mp8
      restartPolicy: Always

      containers:
      # ----------------------------------------------------
      - name: cluster-data-node-2
        image: hub.askug.net/mysql-cluster-data-node-sb-11:0.0.1
        args: [ "-c", "
          while true; do
            /usr/sbin/ndbd
              --nodaemon
            ;
          done;
          tail -f /dev/null # for debug purpose
          " ]

        volumeMounts:
        - mountPath: "/etc/my.cnf"
          name: data-node-config
          subPath: "my.cnf"
          readOnly: true
        - mountPath: "/var/lib/mysql/data"
          name: mysql-data-volume
          subPath: "mysql-data"

        env:
        - name: MYSQL_CLUSTER_DATA_NODE_VERSION
          value: 8.1.0-1

        resources:
          limits:
            memory: 4Gi
            cpu: "4"
          requests:
            memory: 2Gi
            cpu: "2"

        # startupProbe:
        #   tcpSocket:
        #     host: mysql-cluster-discovery-srv-service.mysql-cluster.svc.kube.askug.net
        #     port: 53
        #   initialDelaySeconds: 5
        #   periodSeconds: 10

      # dnsPolicy: "None"
      # dnsConfig:
      #   nameservers:
      #   - 10.216.80.34

      volumes:
      - name: data-node-config
        configMap:
          name: mysql-cluster-node-config
      - name: mysql-data-volume
        persistentVolumeClaim:
          claimName: mysql-cluster-data-node-mp8

...
