FROM busybox:1.36

LABEL maintainer="zoosmand@gmail.com"
LABEL build_date="2024-01-06"
LABEL app_name="mysql-cluster-sb-11"
LABEL app_version="0.0.1"
LABEL name="Test Entrypoint"

ARG BUILD_VERSION=0.0.1

ENTRYPOINT [ "/bin/sh" ]
CMD [ "-c", "" ]
