# Kubernetes Deployment Makefile


.PHONY: all
all:
	# ---
	@ echo "It works!"


.PHONY: apply
apply:
	$(MAKE) -C ./00-common apply


.PHONY: update
update:
	$(MAKE) -C ./00-common update


.PHONY: delete
delete:
	$(MAKE) -C ./00-common delete


.PHONY: cleanup
cleanup:
	$(MAKE) -C ./00-common cleanup
