---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ndb-cluster-balancer-config
  namespace: ndb-cluster
immutable: true
data:
  haproxy.cfg: |+
    global
      log /dev/log    local0
      log /dev/log    local1 notice
      stats socket /var/lib/haproxy/admin.sock mode 660 level admin expose-fd listeners
      stats timeout 30s
      user haproxy

      # Default SSL material locations
      ca-base /etc/ssl/certs
      crt-base /etc/ssl/private

      # See: https://ssl-config.mozilla.org/#server=haproxy&server-version=2.0.3&config=intermediate
      ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
      ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
      ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

    defaults
      log     global
      mode    tcp
      option  tcplog
      option  dontlognull
      timeout connect 5000
      timeout client  50000
      timeout server  50000

    frontend mysql
      bind :3306
      mode tcp
      default_backend mysql_backend
    frontend mysqlx
      bind :33060
      mode tcp
      default_backend mysqlx_backend

    backend mysql_backend
      mode tcp
      server mysql-mp1 ndb-cluster-server-0.ndb-cluster-server-service.ndb-cluster.svc.kube.askug.net:3306 check
      server mysql-mp8 ndb-cluster-server-1.ndb-cluster-server-service.ndb-cluster.svc.kube.askug.net:3306 check backup
    backend mysqlx_backend
      mode tcp
      server mysql-mp1 ndb-cluster-server-0.ndb-cluster-server-service.ndb-cluster.svc.kube.askug.net:33060 check
      server mysql-mp8 ndb-cluster-server-1.ndb-cluster-server-service.ndb-cluster.svc.kube.askug.net:33060 check backup

    listen stats
      bind *:9000
      mode http
      stats enable
      stats uri /
      stats refresh 60s
      stats admin if LOCALHOST


...
